env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    -Xmx756m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -Dspotless.apply.skip=true
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v3
      with:
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gs-${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build GeoServer modules and extensions without tests
      run: 'mvn --version

        mvn -B -ntp -U -T3 -DskipTests -Prelease -f src/pom.xml install

        '
    - continue-on-error: true
      name: Package GeoServer modules and extensions
      run: 'mvn -B -ntp -nsu -N -f src/pom.xml assembly:single

        '
    - continue-on-error: true
      name: Build community modules without tests
      run: 'mvn -B -ntp -U -T3 -DskipTests -PcommunityRelease -f src/community/pom.xml
        install

        '
    - continue-on-error: true
      name: Package community modules
      run: 'mvn -B -ntp -nsu -N -f src/community/pom.xml assembly:single

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

        '
    strategy:
      matrix:
        include:
        - dist: temurin
          jdk: 11
          os: ubuntu-20.04
name: Assembly GitHub CI
on:
  repository_dispatch:
    types: trigger-ga___assembly.yml
