env:
  MAVEN_OPTS: -Xmx1024m -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    -Dspotless.apply.skip=true
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 500
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v3
      with:
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gs-${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn --version

        mvn -B -ntp -U -T3 -fae -Prelease -f src/pom.xml clean install

        '
    - continue-on-error: true
      name: Build community modules without tests
      run: 'mvn -B -ntp -nsu -U -T4 -fae -DskipTests -PcommunityRelease -f src/community/pom.xml
        clean install

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: 'find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

        '
    strategy:
      fail-fast: false
      matrix:
        dist:
        - temurin
        jdk:
        - 11
        - 17
        - 21
        os:
        - ubuntu-20.04
name: Linux JDK GitHub CI
on:
  repository_dispatch:
    types: trigger-ga___linux.yml
