concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  appschema-postgis:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: amrocha/postgis-action@v2
      with:
        postgresql db: appschema
        postgresql password: geoserver
        postgresql user: geoserver
        postgresql version: 15-3.4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Maven repository caching
      uses: actions/cache@v2
      with:
        key: gt-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'gt-maven-

          '
    - continue-on-error: true
      name: Build GeoServer dependent modules (no tests, prepare fresh artifacts)
      run: mvn -B clean install -T2 -U --file src/pom.xml -Prelease,app-schema-online-test
        -DskipTests -pl :gs-app-schema-postgis-test -am -Dspotless.apply.skip=true
    - continue-on-error: true
      name: Build PostGIS app-schema online tests
      run: 'mkdir ~/.geoserver

        cat <<EOT >>   ~/.geoserver/postgis.properties

        user=geoserver

        port=5432

        password=geoserver

        passwd=geoserver

        url=jdbc\:postgresql\://localhost/appschema

        host=localhost

        database=appschema

        driver=org.postgresql.Driver

        EOT

        mvn -B clean install -nsu --file src/pom.xml -Prelease,app-schema-online-test
        -pl :gs-app-schema-postgis-test -Dspotless.apply.skip=true

        '
    - continue-on-error: true
      name: Remove SNAPSHOT jars from repository
      run: "find ~/.m2/repository -name \"*SNAPSHOT*\" -type d | xargs rm -rf {} \n"
name: PostGIS app-schema online tests
on:
  repository_dispatch:
    types: trigger-ga___postgis_appschema_online.yml
